name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-test:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run build-storybook
      - run: yarn run loki:test
